local config = {}

-- AIDA64 RemoteSensor server on the Windows host.
config.host = "192.168.0.232"
config.port = 9999
config.layout_path = "/"
config.path = "/sse"
-- AIDA64 uses Tahoma as its default LCD family. The device keeps that logical
-- family while rasterizing the bundled OFL-licensed Chinese face as a safe
-- fallback; uploading tahoma.ttf makes the logical and physical faces match.
config.vector_font_family = "Tahoma"
config.vector_font_fallback_family = "AIDA Noto Sans SC"
config.vector_font_module = "/sd/apps/aida_monitor/modules/aida_font.so"
config.vector_font_path = "/sd/apps/aida_monitor/font/aida_noto_sans_sc.ttf"
config.vector_font_default_path = "/sd/apps/aida_monitor/font/aida_noto_sans_sc.ttf"
-- WebUI stores one user-supplied TTF here. It is selected only when its
-- configured family is present in the current AIDA64 layout; otherwise the
-- bundled Chinese fallback above remains active.
config.vector_font_custom_family = ""
config.vector_font_custom_path = "/sd/apps/aida_monitor/font/uploaded.ttf"
config.vector_font_custom_name = ""
config.vector_font_custom_bytes = 0
config.font_upload_max_bytes = 4194304
-- LCD stripe order. Use "bgr" if colored fringes look reversed, or "off"
-- when the panel/optics do not preserve physical subpixels.
config.font_subpixel = "rgb"
-- LEFT/RIGHT are generated by HoloCubic's gravity sensor. The cooldown absorbs
-- the START+SHORT burst so one physical tilt changes exactly one page.
config.tilt_page_cooldown_ms = 1000

config.timeout_ms = 7000
config.reconnect_ms = 2000
config.stale_ms = 5000
config.watchdog_ms = 1000
config.layout_retry_ms = 3000
config.reload_delay_ms = 500
config.max_layout_bytes = 196608
config.history_points = 96
config.cache_dir = "/sd/apps/aida_monitor/cache"
config.max_image_bytes = 262144
config.max_image_pixels = 307200
config.image_timeout_ms = 7000
config.serial_log = true

return config
