#!/usr/bin/env python3
"""Inspect the runtime HTML/SSE ABI generated by an AIDA64 RemoteSensor host."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import time
import urllib.request
from collections import Counter
from pathlib import Path


ID_PATTERN = re.compile(
    r'<(?:div|span|canvas|img)\b[^>]*\bid=["\']([^"\']+)["\']', re.IGNORECASE
)
CALL_PATTERN = re.compile(r'\b(DrawGraph|DrawArcGauge)\s*\((.*?)\)\s*;', re.DOTALL)
FUNCTION_PATTERNS = (
    re.compile(r'\bfunction\s+(DrawGraph|DrawArcGauge|ClearGraph)\s*\(([^)]*)\)', re.IGNORECASE),
    re.compile(r'\bvar\s+(DrawGraph|DrawArcGauge|ClearGraph)\s*=\s*function\s*\(([^)]*)\)', re.IGNORECASE),
)
BACKGROUND_PATTERN = re.compile(
    r'background-image\s*:\s*url\s*\(\s*(["\']?)(.*?)\1\s*\)', re.IGNORECASE
)


def fetch(url: str, timeout: float) -> bytes:
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "text/html,application/xhtml+xml",
            "Accept-Encoding": "identity",
            "Cache-Control": "no-cache",
            "User-Agent": "HoloCubic-RemoteSensor-Probe/1.0",
        },
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read()


def split_js_arguments(raw: str) -> list[str]:
    values: list[str] = []
    current: list[str] = []
    quote = ""
    escaped = False
    depth = 0
    for char in raw:
        if escaped:
            current.append(char)
            escaped = False
        elif quote and char == "\\":
            current.append(char)
            escaped = True
        elif quote:
            current.append(char)
            if char == quote:
                quote = ""
        elif char in "\"'":
            current.append(char)
            quote = char
        elif char in "([{" :
            current.append(char)
            depth += 1
        elif char in ")]}":
            current.append(char)
            depth = max(0, depth - 1)
        elif char == "," and depth == 0:
            values.append("".join(current).strip())
            current = []
        else:
            current.append(char)
    values.append("".join(current).strip())
    return values


def inspect_html(data: bytes) -> dict[str, object]:
    text = data.decode("utf-8", errors="replace")
    ids = ID_PATTERN.findall(text)
    prefixes = Counter(re.match(r"[A-Za-z]+", value).group(0) for value in ids if re.match(r"[A-Za-z]+", value))
    functions = {}
    for pattern in FUNCTION_PATTERNS:
        for name, parameters in pattern.findall(text):
            functions[name] = [part.strip() for part in parameters.split(",") if part.strip()]
    calls = []
    for name, arguments in CALL_PATTERN.findall(text):
        fields = split_js_arguments(arguments)
        calls.append({"function": name, "id": fields[0] if fields else "", "arguments": fields})
    background = BACKGROUND_PATTERN.search(text)
    return {
        "bytes": len(data),
        "sha256": hashlib.sha256(data).hexdigest(),
        "ids": ids,
        "id_prefix_counts": dict(sorted(prefixes.items())),
        "background_image": background.group(2) if background else None,
        "function_signatures": functions,
        "canvas_calls": calls,
    }


def sample_sse(url: str, timeout: float, seconds: float, max_records: int) -> dict[str, object]:
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "text/event-stream",
            "Cache-Control": "no-cache",
            "User-Agent": "HoloCubic-RemoteSensor-Probe/1.0",
        },
    )
    deadline = time.monotonic() + seconds
    payloads: list[str] = []
    commands: Counter[str] = Counter()
    with urllib.request.urlopen(request, timeout=timeout) as response:
        while time.monotonic() < deadline and len(payloads) < max_records:
            line = response.readline()
            if not line:
                break
            decoded = line.decode("utf-8", errors="replace").rstrip("\r\n")
            if not decoded.startswith("data:"):
                continue
            payload = decoded[5:].lstrip()
            payloads.append(payload)
            for record in payload.split("{|}"):
                command = record.split("|", 1)[0]
                if command:
                    prefix = re.match(r"[A-Za-z]+", command)
                    commands[prefix.group(0) if prefix else command] += 1
    return {"payloads": payloads, "command_prefix_counts": dict(sorted(commands.items()))}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="192.168.0.232")
    parser.add_argument("--port", type=int, default=9999)
    parser.add_argument("--layout-path", default="/")
    parser.add_argument("--sse-path", default="/sse")
    parser.add_argument("--timeout", type=float, default=7.0)
    parser.add_argument("--sse-seconds", type=float, default=2.0)
    parser.add_argument("--max-sse-records", type=int, default=3)
    parser.add_argument("--html-out", type=Path)
    parser.add_argument("--json-out", type=Path)
    args = parser.parse_args()

    base = f"http://{args.host}:{args.port}"
    layout_path = "/" + args.layout_path.lstrip("/")
    sse_path = "/" + args.sse_path.lstrip("/")
    html = fetch(base + layout_path, args.timeout)
    result = {
        "source": base,
        "layout": inspect_html(html),
        "sse": sample_sse(base + sse_path, args.timeout, args.sse_seconds, args.max_sse_records),
    }
    if args.html_out:
        args.html_out.write_bytes(html)
    rendered = json.dumps(result, ensure_ascii=False, indent=2) + "\n"
    if args.json_out:
        args.json_out.write_text(rendered, encoding="utf-8")
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
